name: Build Image
description: 'Build Docker image'
inputs:
  image:
    description: 'Name of the image to build'
    required: true
runs:
  using: composite
  steps:
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
    - name: Set environment variables
      run: echo "IMAGE_NAME=${{ inputs.image }}" >> $GITHUB_ENV
      shell: bash
    - name: Build and publish Docker image using Gradle
      run: |
        ./gradlew bootBuildImage
        docker push $IMAGE_NAME
      shell: bash
