name: Build Image
description: 'Build Docker image'
inputs:
  image:
    description: 'Name of the image to build'
    required: true
  registry_username:
    description: 'Username of the release registry'
    required: true
  registry_password:
    description: 'Password of the release registry'
    required: true
runs:
  using: composite
  steps:
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
    - name: Set environment variables
      run: echo "IMAGE_NAME=${{ inputs.image }}" >> $GITHUB_ENV
      shell: bash
    - name: Build Docker image using Gradle
      run: ./gradlew bootBuildImage --imageName=$IMAGE_NAME
      shell: bash
    - name: Login to target Docker repository
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}
    - name: Publish Docker image
      run: docker push $IMAGE_NAME
      shell: bash
