name: Build and Test
description: 'Build and test all modules'
runs:
  using: composite
  steps:
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
    - name: Build with Gradle
      run: ./gradlew build
      shell: bash
    - name: Store test files
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: test-results
        path: |
          ./build/reports
          ./build/test-results/**/*.xml
    - name: Create test report dorny
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: JUnit Tests
        path: ./build/test-results/test/*.xml
        reporter: java-junit
