name: 'Build and Test'
description: 'Build and test all modules'
runs:
  using: composite
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
    - name: Build with Gradle
      run: ./gradlew build
      shell: bash
    - name: Create test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: JUnit Tests
        path: ./demo/build/test-results/test/*.xml
        reporter: java-junit
