name: 'Build and Test'
description: 'Build and test all modules'
inputs:
  jdk_version:
    description: 'The version of JDK to use'
    required: false
    default: '17'
runs:
  using: composite
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.jdk_version }}
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
    - name: Build with Gradle
      run: ./gradlew build
      shell: bash
