name: CI
on:
  push:
    branches:
      - 'develop'
      - 'release/**'
      - 'hotfix/**'
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - 'develop'
      - 'release/**'
      - 'hotfix/**'
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build and test
        uses: ./.github/actions/build-and-test
      - name: Build Docker image
        uses: ./.github/actions/build-image
        with:
          image: ghcr.io/$GITHUB_REPOSITORY_OWNER/demo-app:${GITHUB_REF_NAME::1}-$GITHUB_RUN_NUMBER
          registry_username: $GITHUB_ACTOR
          registry_password: ${{ secrets.GITHUB_TOKEN }}
