name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build app
        run: |
          echo 'Building app...'
          echo 'Building app complete.'

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Publis to prod
        run: |
          echo 'Publishing to prod...'
          echo 'Publish to prod complete..'
