name: Install Test
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to install'
        required: true
jobs:
  install:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: Release local image
        uses: ./.github/actions/release-image
        with:
          source_image: ghcr.io/$GITHUB_REPOSITORY_OWNER/demo-app:${{ github.event.inputs.image_tag }}
          target_repo_username: ${{ secrets.DOCKERHUB_USERNAME }}
          target_repo_password: ${{ secrets.DOCKERHUB_TOKEN }}
          target_image: ${{ secrets.DOCKERHUB_USERNAME }}/test:${{ github.event.inputs.image_tag }}
