name: Install Test
on:
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Print
        run: |
          env
          echo ${{ vars.TEST }}
