name: Install Prod
on:
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Print
        run: |
          env
          echo ${{ vars.TEST }}
