name: Release Start
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v3
      - name: Verify develop branch
        if: github.ref != 'refs/heads/develop'
        run: exit 1
      - name: Create release branch
        run: |
          git branch release/${{ github.event.inputs.version }}
          git push origin release/${{ github.event.inputs.version }}
      - name: Start CI workflow for release branch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: CI
          ref: release/${{ github.event.inputs.version }}
