name: Release Finish
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Verify release branch
        if: startsWith(github.ref, 'refs/heads/release/')
      - name: Create release branch
        run: |
          git branch
          git status
