name: Release Start
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v3
      - name: Create release branch
        uses: ./.github/actions/start-branch
        with:
          source_branch: develop
          target_branch: release/${{ github.event.inputs.version }}
