name: Release Finish
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Verify release branch
        if: ${{ !startsWith(github.ref, 'refs/heads/release/') }}
        run: exit 1
      - name: Set version number
        run: |
          echo "VERSION_NUMBER=$(echo ${{ github.ref }} | awk -F/ '{print $NF}')" >> $GITHUB_ENV
          echo "VERSION_NUMBER=$(echo ${{ github.ref }} | awk -F/ '{print $NF}')"
          echo Using version number ${{ vars.VERSION_NUMBER }}
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Merge release branch to develop and main
        run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff ${{ github.ref }} -m "Auto-merge release branch ${{ github.ref }} to develop"
          git push
          git checkout main
          git pull
          git merge --no-ff ${{ github.ref }} -m "Auto-merge release branch ${{ github.ref }} to main"
          git push
      - name: Delete relese branch
        run: git push origin --delete ${{ github.ref }}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $VERSION_NUMBER
          release_name: Release $VERSION_NUMBER
