name: Run
on:
  workflow_dispatch:
    inputs:
      param:
        description: 'Test param'
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Step 1
        run:  |
          if [[ "${{ inputs.param }}" == *":"* ]]; then
            base_image=$(echo ${{ inputs.param }} | sed 's/:/-base&/')
          else
            base_image="${{ inputs.param }}-base"
          fi
          echo $base_image
      - name: Step 2
        run:  |
          filename="./src/main/resources/application.yml"
          if [[ -f "$filename" ]]; then
            echo "File ${filename} exists."
          else
            echo "File ${filename} not exists."
          fi
