name: Test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: ls -lash .github/actions/
      - name: Release local image
        uses: ./.github/actions/release-image
        with:
          source_image: ghcr.io/${{ github.repository_owner }}/demo-app:latest
          target_repo_username: ${{ secrets.DOCKERHUB_USERNAME }}
          target_repo_password: ${{ secrets.DOCKERHUB_TOKEN }}
          target_image: ${{ secrets.DOCKERHUB_USERNAME }}/test:latest
