name: Test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Test action use
        uses: ./.github/actions/test
        with:
          param1: ${GITHUB_REF_NAME##*/}
          param2: ${GITHUB_REF_NAME::1}
