name: Test2
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        uses: ./.github/actions/build-image
        with:
          image: ghcr.io/${{ github.repository_owner }}/demo-app:latest
          registry_username: $GITHUB_ACTOR
          registry_password: ${{ secrets.GITHUB_TOKEN }}
