name: Test

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Retag local image
        run:  |
          docker pull ghcr.io/${{ github.repository_owner }}/demo-app:latest
          docker tag ghcr.io/${{ github.repository_owner }}/demo-app:latest anttihuokkosolita/test:latest
          docker images
